export {default as About} from './About/About'
export {default as Footer} from './Footer/Footer'
export {default as Header} from './Header/Header'
export {default as Reviews} from './Reviews/Reviews'
export {default as WhyUs} from './WhyUs/WhyUs'
export {default as Contact} from './Contact/Contact'
